export type ModelCapabilityType = 'text_llm' | 'vision_ocr' | 'multimodal' | 'embedding';

export type ModelConnectionProtocol = 'openai_compatible';

export type ModelConnectionConfig = {
  id: string;
  label: string;
  presetId: string;
  protocol: ModelConnectionProtocol;
  baseUrl: string;
  apiKey: string;
  enabled: boolean;
  local?: boolean;
};

export type SystemModelSlotId = 'language' | 'vision';

export type SystemModelSlotConfig = {
  id: SystemModelSlotId;
  label: string;
  description: string;
  providerId: string;
  modelName: string;
  enabled: boolean;
  capabilities: Array<'text' | 'reasoning' | 'vision' | 'document'>;
};

export type ModelProviderConfig = {
  id: string;
  providerId?: string;
  label: string;
  agentName: string;
  description: string;
  capabilityType: ModelCapabilityType;
  capabilities: string[];
  modelName: string;
  apiKey: string;
  baseUrl: string;
  enabled: boolean;
  ocrFormats?: string;
  infraNote?: string;
};

export type ApiIntegrationType = 'rest_api' | 'ocr_service' | 'search_api' | 'export_pipeline' | 'vector_rag';

export type ApiProviderConfig = {
  id: string;
  providerId?: string;
  name: string;
  category: string;
  purpose: string;
  integrationType: ApiIntegrationType;
  dependsOn?: string[];
  apiKey: string;
  endpoint: string;
  enabled: boolean;
};

export type McpToolConfig = {
  skill_name: string;
  skill_type: 'local_mcp';
  enabled?: boolean;
  authorizedAgents?: string[];
  display_name_zh: string;
  display_name_en?: string;
  description_zh: string;
  description_en?: string;
  /** Python MCP server source maintained by the admin tool editor. */
  source_code?: string;
  /** Runtime entry generated by the backend when the tool is saved. */
  entry_file?: string;
  mcp_server_config: {
    command: string;
    args: string[];
  };
};

export type AdminSettings = {
  modelProviders: ModelConnectionConfig[];
  modelSlots: SystemModelSlotConfig[];
  /** Legacy per-role model settings. Retained during the migration window. */
  models: ModelProviderConfig[];
  apis: ApiProviderConfig[];
  routingRules: string[];
  reviewRules: string[];
  mcpTools?: McpToolConfig[];
};

export const DEFAULT_MODEL_CONNECTIONS: ModelConnectionConfig[] = [
  { id: 'openai', label: 'OpenAI', presetId: 'openai', protocol: 'openai_compatible', baseUrl: 'https://api.openai.com/v1', apiKey: '', enabled: false },
  { id: 'gemini', label: 'Google Gemini', presetId: 'gemini', protocol: 'openai_compatible', baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai/', apiKey: '', enabled: false },
  { id: 'openrouter', label: 'OpenRouter', presetId: 'openrouter', protocol: 'openai_compatible', baseUrl: 'https://openrouter.ai/api/v1', apiKey: '', enabled: false },
  { id: 'deepseek', label: 'DeepSeek', presetId: 'deepseek', protocol: 'openai_compatible', baseUrl: 'https://api.deepseek.com/v1', apiKey: '', enabled: true },
  { id: 'qwen', label: '通义千问', presetId: 'qwen', protocol: 'openai_compatible', baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1', apiKey: '', enabled: false },
  { id: 'zhipu', label: '智谱 GLM', presetId: 'zhipu', protocol: 'openai_compatible', baseUrl: 'https://open.bigmodel.cn/api/paas/v4', apiKey: '', enabled: false },
  { id: 'moonshot', label: 'Kimi / Moonshot', presetId: 'moonshot', protocol: 'openai_compatible', baseUrl: 'https://api.moonshot.cn/v1', apiKey: '', enabled: false },
  { id: 'custom', label: '自定义兼容接口', presetId: 'custom', protocol: 'openai_compatible', baseUrl: '', apiKey: '', enabled: false },
];

export const DEFAULT_SYSTEM_MODEL_SLOTS: SystemModelSlotConfig[] = [
  {
    id: 'language',
    label: '主语言模型',
    description: '统一用于任务规划、法律分析、文书生成与结果复核。',
    providerId: 'deepseek',
    modelName: 'deepseek-v4-flash',
    enabled: true,
    capabilities: ['text', 'reasoning'],
  },
  {
    id: 'vision',
    label: '视觉理解模型',
    description: '用于图片、扫描件、复杂 PDF 与表格内容理解。',
    providerId: 'qwen',
    modelName: 'qwen-vl-max',
    enabled: true,
    capabilities: ['vision', 'document'],
  },
];

export const DEFAULT_MODEL_CONFIGS: ModelProviderConfig[] = [
  {
    id: 'planner',
    label: '任务理解模型',
    agentName: '任务理解智能体',
    description: '负责场景识别、任务拆解与调度建议。',
    capabilityType: 'text_llm',
    capabilities: ['场景识别', '任务拆解', '调度建议'],
    modelName: '',
    apiKey: '',
    baseUrl: '',
    enabled: true,
  },
  {
    id: 'vision',
    label: '证据质检模型',
    agentName: '证据质检智能体',
    description: '负责 OCR、材料解析与证据缺口识别。',
    capabilityType: 'vision_ocr',
    capabilities: ['OCR 识图', 'PDF 解析', '证据链整理', '缺口识别'],
    modelName: '',
    apiKey: '',
    baseUrl: '',
    enabled: true,
    ocrFormats: 'PDF、JPG、PNG、扫描件',
    infraNote: '需配置视觉模型或独立 OCR 服务，可与下方 API 工具链联动。',
  },
  {
    id: 'research',
    label: '法规研究模型',
    agentName: '法规研究智能体',
    description: '负责法规检索、案例引用与研究结论生成。',
    capabilityType: 'text_llm',
    capabilities: ['法规检索', '案例引用', '研究摘要'],
    modelName: '',
    apiKey: '',
    baseUrl: '',
    enabled: true,
  },
  {
    id: 'drafting',
    label: '文书生成模型',
    agentName: '文书生成智能体',
    description: '负责报告、律师函、意见书等结构化输出。',
    capabilityType: 'text_llm',
    capabilities: ['结构化写作', '模板填充', '多轮修订'],
    modelName: '',
    apiKey: '',
    baseUrl: '',
    enabled: true,
  },
  {
    id: 'review',
    label: '交叉审查模型',
    agentName: '交叉审查智能体',
    description: '负责事实、证据、法规与文书一致性复核。',
    capabilityType: 'multimodal',
    capabilities: ['事实核验', '法规适配', '风险表达审查'],
    modelName: '',
    apiKey: '',
    baseUrl: '',
    enabled: true,
    infraNote: '可结合文本模型 + 规则引擎，高风险场景强制触发。',
  },
];

export const DEFAULT_API_CONFIGS: ApiProviderConfig[] = [
  { id: 'ocr', name: 'OCR / 文档解析', category: '材料处理', purpose: '识别合同、扫描件与 PDF 材料。', integrationType: 'ocr_service', dependsOn: ['vision'], apiKey: '', endpoint: 'https://aip.baidubce.com/rest/2.0/ocr/v1/accurate_basic', enabled: true },
  { id: 'legal_search', name: '得理法律检索', category: '法律研究', purpose: '检索法规、司法解释与裁判案例。', integrationType: 'search_api', dependsOn: ['research'], apiKey: '', endpoint: 'https://openapi.delilegal.com', enabled: true },
  { id: 'contract_documents', name: '合同文书引擎', category: '合同文书', purpose: 'LLM + 法规/模板检索：审查报告、商业合同起草、条款修改备忘，支持 DOCX/PDF 导出。', integrationType: 'rest_api', dependsOn: ['drafting', 'research'], apiKey: '', endpoint: '', enabled: true },
  { id: 'contract_review_external', name: '第三方审查文档交付（可选）', category: '合同文书', purpose: '百度 TextReview 等异步生成批注版合同与审查报告下载链接，不作为对话式分析结论。', integrationType: 'rest_api', dependsOn: ['review'], apiKey: '', endpoint: 'https://aip.baidubce.com', enabled: false },
  { id: 'contract_compare', name: '合同版本比对（本地）', category: '合同审查', purpose: '多版本合同 diff、增删改统计与修订痕迹，适合续签与谈判场景，无需外部 Key。', integrationType: 'rest_api', dependsOn: ['review'], apiKey: '', endpoint: '/api/demo/contract/compare', enabled: true },
  { id: 'web_search', name: '联网搜索', category: '公开资料', purpose: '补充公开资料与行业背景。', integrationType: 'search_api', apiKey: '', endpoint: 'https://api.tavily.com/search', enabled: false },
  { id: 'export', name: '文书导出', category: '结果交付', purpose: '导出 PDF / DOCX / 材料包。', integrationType: 'export_pipeline', dependsOn: ['drafting'], apiKey: '', endpoint: '', enabled: true },
  { id: 'vector_rag', name: '本地知识库 / RAG', category: '知识增强', purpose: '接入法规库、模板库与案例库。', integrationType: 'vector_rag', dependsOn: ['research', 'drafting'], apiKey: '', endpoint: './chroma_lexhub', enabled: true },
];

export type ApiConfigGuidance = {
  keyPlaceholder: string;
  endpointPlaceholder: string;
  hint: string;
};

export const API_CONFIG_GUIDANCE: Record<string, ApiConfigGuidance> = {
  ocr: {
    keyPlaceholder: 'BAIDU_OCR_API_KEY|BAIDU_OCR_SECRET_KEY',
    endpointPlaceholder: 'https://aip.baidubce.com/rest/2.0/ocr/v1/accurate_basic',
    hint: '在百度智能云创建文字识别应用后，将 API Key 与 Secret Key 用竖线连接后保存；也可分别写入 .env。',
  },
  legal_search: {
    keyPlaceholder: '得理 App Secret 或 LEGAL_SEARCH_API_KEY',
    endpointPlaceholder: 'https://openapi.delilegal.com',
    hint: '在得理开放平台申请 AppID + Secret，写入 .env 的 DELILEGAL_APPID / DELILEGAL_SECRET，或在此填写 Key 后保存。',
  },
  web_search: {
    keyPlaceholder: 'TAVILY_API_KEY',
    endpointPlaceholder: 'https://api.tavily.com/search',
    hint: '公开网页检索使用 Tavily；Wikipedia 作为无需 Key 的百科补充工具，由法规研究智能体按需调用。',
  },
  export: {
    keyPlaceholder: '一般无需 Key',
    endpointPlaceholder: '导出服务地址（本地导出可留空）',
    hint: '本地 DOCX/PDF 导出无需 Key；.env 中 DOCX_EXPORT_ENABLED=true 即可。暂未接第三方导出流水线时可保持停用。',
  },
  vector_rag: {
    keyPlaceholder: '本地 Chroma 无需 Key',
    endpointPlaceholder: './chroma_lexhub',
    hint: '与 .env 的 CHROMA_PERSIST_DIR 一致。在「知识库」页导入合同种子包后，智能工作台任务结果即可引用模板。',
  },
  contract_documents: {
    keyPlaceholder: '复用「任务理解模型」API_KEY，一般无需单独填写',
    endpointPlaceholder: '留空即可',
    hint: '在 .env 配置 LLM（API_KEY）与知识库（CHROMA_PERSIST_DIR）后，智能工作台选场景填表单，于任务结果生成文书。',
  },
  contract_review_external: {
    keyPlaceholder: 'BAIDU_TEXTREVIEW_API_KEY|BAIDU_TEXTREVIEW_SECRET_KEY',
    endpointPlaceholder: 'https://aip.baidubce.com',
    hint: '可选外部审查；需公网文件 URL。演示推荐用内置「合同文书引擎」。',
  },
  contract_compare: {
    keyPlaceholder: '比对服务 API Key',
    endpointPlaceholder: '文档比对 API 地址',
    hint: '适合续签、谈判轮次多版本合同 diff；可与 OCR 流水线串联。',
  },
};

export const DEFAULT_ROUTING_RULES = [
  '材料完整度低于 70%，优先调度证据质检智能体。',
  '法规引用缺失或争议焦点不明确，调度法规研究智能体。',
  '用户目标为报告、律师函或意见书，调度文书生成智能体。',
  '高风险、低置信度或导出前，强制调度交叉审查智能体。',
];

export const DEFAULT_REVIEW_RULES = [
  '事实一致性：主体、金额、时间线是否互相冲突。',
  '证据支撑性：结论是否有材料或 OCR 结果支撑。',
  '法规适配性：引用是否匹配当前争议焦点。',
  '文书安全性：是否存在绝对化、越权或幻觉风险表达。',
];

export function createDefaultAdminSettings(): AdminSettings {
  return {
    modelProviders: DEFAULT_MODEL_CONNECTIONS.map((item) => ({ ...item })),
    modelSlots: DEFAULT_SYSTEM_MODEL_SLOTS.map((item) => ({ ...item, capabilities: [...item.capabilities] })),
    models: DEFAULT_MODEL_CONFIGS.map((item) => ({ ...item })),
    apis: DEFAULT_API_CONFIGS.map((item) => ({ ...item })),
    routingRules: [...DEFAULT_ROUTING_RULES],
    reviewRules: [...DEFAULT_REVIEW_RULES],
    mcpTools: [],
  };
}
